config/routes.rb
Rails.application.routes.draw do
  root 'menu_items#index'
  get 'menu_items', to: 'menu_items#index'
  get 'menu_items/menu/:id', to: 'menu_items#show_menu', as: 'menu'
  get 'menu_items/new', to: 'menu_items#new'
  get 'menu_items/:id', to: 'menu_items#show', as: 'menu_item'
  post 'menu_items', to: 'menu_items#create'
  post 'menu_items/:id/add', to: 'menu_items#add_to_order', as: 'add_to_order'
  get 'menu_items/:id/edit', to: 'menu_items#edit', as: 'edit_menu_item'
  patch 'menu_items/:id', to: 'menu_items#update'
  delete 'menu_items/:id', to: 'menu_items#destroy'

  get 'order_menu_items', to: 'order_menu_items#index'
  post 'order_menu_items', to: 'order_menu_items#create'
  patch 'order_menu_items/:id', to: 'order_menu_items#update'
  delete 'order_menu_items/delete_all', to: 'order_menu_items#destroy_all_items', as: 'destroy_all_items'
  delete 'order_menu_items/:id', to: 'order_menu_items#destroy'

  get 'payments/success', to: 'payments#success'
  post 'payments/webhook', to: 'payments#webhook'

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    belongs_to :user
    has_one_attached :photo, dependent: :destroy
    has_many :order_menu_items, dependent: :destroy
    has_many :orders, through: :order_menu_items, dependent: :destroy
    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 30, maximum: 400 }
    validates :price, presence: true, numericality: { in: 1..99 }
    after_commit :add_default_photo, on: [:create, :update]

    private

    def add_default_photo
        unless photo.attached?
            self.photo.attach(io: File.open(Rails.root.join("app", "assets", "images", "no-img.png")), filename: 'no-img.png', content_type: "image/png")
        end
    end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  # DEBUG ONLY - REMOVE FOR PRODUCTION!
  # skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:index]
  before_action :check_auth
  before_action :set_menu_item, only: [:show, :update, :edit, :destroy, :add_to_order]
  before_action :set_order, only: [:show_menu, :add_to_order]

  def index
    if user_signed_in? && current_user.has_role?(:restaurant)
      # Querying user only with required fields for the view (full_name and id)
      # Eager loading used to query Users, MenuItems, and Attachment all at once

      # When the user is a restaurant, only its restaurant will be displayed
      @restaurants = User.select(:full_name, :id).includes(menu_items: [:photo_attachment]).where(id: current_user.id)
    else
      # When user is a customer, all restaurants will be displayed
      @restaurants = Role.find_by_name('restaurant').users.select(:full_name, :id).includes(menu_items: [:photo_attachment])
    end
  end

  def show_menu
    # Finding the requested restaurant
    # Querying only the attributes required in the view file
    # Using eager loading to query User, MenuItems and Attachment at once to minimise db calls in the view loop
    @restaurant = User.select(:full_name, :id).includes(menu_items: [:photo_attachment]).find(params[:id])
    # Defining an array with all menu_items associated with the chosen restaurant
    @menu = @restaurant.menu_items
  end

  def show
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.create(menu_item_params)
    if @menu_item.valid?
      redirect_to @menu_item
    else
      flash.now[:alert] = @menu_item.errors.full_messages.join('<br>')
      render 'new'
    end
  end

  def add_to_order
    if @order.menu_items.include?(@menu_item)
      item = @menu_item.order_menu_items.find_by_order_id(@order.id)
      quantity = item.quantity.to_i + params[:quantity].to_i
      item.update(quantity: quantity)
    else
      @order.order_menu_items.create!(order_item_params)
    end
    redirect_to order_menu_items_path
  end

  def edit
  end

  def update
    @menu_item.update!(menu_item_params)
    redirect_to @menu_item
  rescue
    flash.now[:alert] = @menu_item.errors.full_messages.join('<br>')
    render 'edit'
  end

  def destroy
    @restaurant_id = @menu_item.user_id
    @menu_item.destroy
    redirect_to menu_path(@restaurant_id)
  end

  private

  def check_auth
    authorize MenuItem
  end

  # Strong params for creating and updating a menu_item
  def menu_item_params
    return params.require(:menu_item).permit(:name, :description, :price, :available, :user_id, :photo)
  end

  # Creating a variable with a specific menu_item to be displayed, updated and deleted
  # Selecting only the attributes needed in views and actions
  def set_menu_item
    @menu_item = MenuItem.select(:id, :user_id, :name, :description, :price, :available).find(params[:id])
  end

  # Setting a session-based order for the current user when accessing the 'Menu Items' page
  def set_order
    @order = Order.find(session[:order_id])
  rescue ActiveRecord::RecordNotFound
    @order = Order.create(user_id: current_user.id)
    session[:order_id] = @order.id
  end

  # Strong params for updating an order_menu_item
  def order_item_params
    return params.permit(:order_id, :menu_item_id, :quantity)
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: @menu_item, data: {turbo: false}) do |f| %>
    <fieldset mb-2">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
    </fieldset>
    
    <fieldset class="mb-2">
        <%= f.label :description, class: "form-label" %>
        <%= f.text_field :description, class: "form-control" %>
    </fieldset>
    
    <fieldset class="mb-2">
        <%= f.label :price, class: "form-label" %>
        <%= f.number_field :price, class: "form-control", minimum: 0 %>
    </fieldset>
    
    <fieldset class="mb-2">
        <%= f.radio_button :available, true, checked: "checked" %>
        <%= f.label :available, "Item is currently available" %>
    </fieldset>
    <fieldset>
        <%= f.radio_button :available, false %>
        <%= f.label :not_available, "Item is SOLD OUT" %>
    </fieldset>
    
    <fieldset>
        <%= f.hidden_field :user_id, value: current_user.id %>
    </fieldset>

    <% if @menu_item.photo.attached? %>
        <fieldset class="my-4">
            <%= cl_image_tag @menu_item.photo.key, transformation: ["media_lib_thumb"], cloud_name: ENV['CLOUDINARY_CLOUD_NAME'] %>
        </fieldset>
    <% end %>
    
    <fieldset class="my-4">
        <%= f.label :photo %>
        <%= f.file_field :photo %>
    </fieldset>
    
    <fieldset>
        <%= f.submit class: "btn btn-outline-success mb-3" %>
    </fieldset>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Edit Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @menu_item %>

app/views/menu_items/index.html.erb
<h1>Restaurants</h1>
<h4 class="mb-4"><em>and their plant-based meals!<em></h4>

<div class="row row-cols-1 row-cols-lg-2">
    <% @restaurants.each do |restaurant| %>
		<div class="col">
			<div class="card my-4" style="max-width: 720px;">
				<div class="row g-0">
					<div class="col-md-5">
						<% if !restaurant.menu_items.empty? %>
							<%= cl_image_tag(restaurant.menu_items.first.photo.key, transformation: [ {gravity: "auto", height: 500, width: 760, crop: "fill"}], cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "img-fluid rounded-start") %>      
						<% else %>
							<%= cl_image_tag("no-img_qrdx6i.png", transformation: [ {gravity: "auto", height: 500, width: 760, crop: "fill"} ], cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "img-fluid rounded-start") %>      
						<% end %>
					</div>
					<div class="col-md-4">
						<div class="card-body">
							<h5 class="card-title"><%= restaurant.full_name %></h5>
						</div>
					</div>
					<div class="col-md-3">
						<div class="card-body">
							<%= link_to "Explore Menu", menu_path(restaurant.id), class: "btn btn-primary" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/menu_items/show.html.erb
<h3 class="mt-2"><%= @menu_item.user.full_name %></h3>

<div class="card my-3 mx-auto" style="max-width: 1000px;">
	<div class="row g-0">
		<div class="col-md-6">
			<%= cl_image_tag(@menu_item.photo.key, crop: 'fill', width: 750, height: 600, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "img-fluid rounded-start") %>
		</div>
		<div class="col-md-6">
			<div class="card-body">
				<h4 class="card-title"><%= @menu_item.name %></h4>
				<p class="card-text">$<%= @menu_item.price %></p>
				<p class="card-text"><%= @menu_item.description %></p>
				<p class="card-text text-muted"><%= "Item is currently SOLD OUT." unless @menu_item.available? %></p>
				<% if user_signed_in? && current_user.has_role?(:customer) && @menu_item.available? %>
					<%= form_with(model: @order_item, url: add_to_order_path) do |f| %>
						<%= f.hidden_field :menu_item_id, value: @menu_item.id %>
						<%= f.number_field :quantity, value: 1, in: 1..20 %>
						<%= f.submit 'Add to Order' %>
					<% end %>					
				<% end %>
			</div>
		</div>
	</div>
</div>

<div class="btn-toolbar my-4 justify-content-center">
	<%= link_to 'Edit', edit_menu_item_path(@menu_item), class: 'menu-btn btn btn-outline-warning me-3 px-4' if policy(@menu_item).edit? %>
	<%= button_to('Delete', @menu_item, class: 'btn btn-outline-danger px-3', method: :delete, form: { data: { turbo_confirm: "Do you want to delete '#{@menu_item.name}' from your menu?" } }) if policy(@menu_item).destroy? %>
</div>

<%= link_to 'Back to Menu', menu_path(@menu_item.user.id) %>

app/views/menu_items/show_menu.html.erb
<h2><%= @restaurant.full_name %>'s Menu</h2>
<%= link_to 'New Menu Item', menu_items_new_path, class: "btn btn-outline-success my-3" if policy(MenuItem).create? %>  

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mt-2 mb-4">
    <% @menu.each do |menu_item| %>
		<div class="col">
			<div class="card h-100">
				<div class="ratio ratio-4x3">
					<%= cl_image_tag(menu_item.photo.key, crop: 'fit', width: 700, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "card-img-top") %>
				</div>    
				<div class="card-body">
					<h5 class="card-title"><%= menu_item.name%></h5>
					<p class="card-text card-price">$<%= menu_item.price %></p>
					<%= link_to "See Details", menu_item, class: "btn btn-primary" %>
				</div>
			</div>
		</div>
    <% end %>
</div>

<%= link_to 'Back to Listing', root_path %>