config/routes.rb
Rails.application.routes.draw do
  root 'menu_items#index'
  get 'menu_items', to: 'menu_items#index'
  get 'menu_items/menu/:id', to: 'menu_items#show_menu', as: 'menu'
  get 'menu_items/new', to: 'menu_items#new'
  get 'menu_items/:id', to: 'menu_items#show', as: 'menu_item'
  post 'menu_items', to: 'menu_items#create'
  post 'menu_items/:id/add', to: 'menu_items#add_to_order', as: 'add_to_order'
  get 'menu_items/:id/edit', to: 'menu_items#edit', as: 'edit_menu_item'
  patch 'menu_items/:id', to: 'menu_items#update'
  delete 'menu_items/:id', to: 'menu_items#destroy'

  get 'order_menu_items', to: 'order_menu_items#index'
  post 'order_menu_items', to: 'order_menu_items#create'
  patch 'order_menu_items/:id', to: 'order_menu_items#update'
  delete 'order_menu_items/delete_all', to: 'order_menu_items#destroy_all_items', as: 'destroy_all_items'
  delete 'order_menu_items/:id', to: 'order_menu_items#destroy'

  get 'payments/success', to: 'payments#success'
  post 'payments/webhook', to: 'payments#webhook'

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark" style="background-color: #2d9148">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><%= cl_image_tag("Vegme-logo_zad1dd.png", crop: 'scale', width: 80, cloud_name: ENV['CLOUDINARY_CLOUD_NAME']) %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <%= link_to "Restaurants", menu_items_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "View Order", order_menu_items_path, class: "nav-link" %>
            </li>
            </ul>
            <% if user_signed_in? %>
            <div class="ml-auto btn-toolbar me-3">
                Welcome, <%= current_user.full_name %>!
            </div>
            <div class="ml-auto btn-toolbar">
                <%= button_to "Logout", destroy_user_session_path, class: "btn btn-light", method: :delete, form: { data: { turbo_confirm: "Do you want to log out?" } } %>
            </div>
            <% else %>
            <div class="ml-auto btn-toolbar p-1">
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light" %>
            </div>
            <div class="ml-auto btn-toolbar p-1">
                <%= link_to "Login", new_user_session_path, class: "btn btn-outline-dark" %>
            </div>
            <% end %>
        </div>
    </div>
</nav>