config/routes.rb
Rails.application.routes.draw do
  root 'menu_items#index'
  get 'menu_items', to: 'menu_items#index'
  get 'menu_items/menu/:id', to: 'menu_items#show_menu', as: 'menu'
  get 'menu_items/new', to: 'menu_items#new'
  get 'menu_items/:id', to: 'menu_items#show', as: 'menu_item'
  post 'menu_items', to: 'menu_items#create'
  post 'menu_items/:id/add', to: 'menu_items#add_to_order', as: 'add_to_order'
  get 'menu_items/:id/edit', to: 'menu_items#edit', as: 'edit_menu_item'
  patch 'menu_items/:id', to: 'menu_items#update'
  delete 'menu_items/:id', to: 'menu_items#destroy'

  get 'order_menu_items', to: 'order_menu_items#index'
  post 'order_menu_items', to: 'order_menu_items#create'
  patch 'order_menu_items/:id', to: 'order_menu_items#update'
  delete 'order_menu_items/delete_all', to: 'order_menu_items#destroy_all_items', as: 'destroy_all_items'
  delete 'order_menu_items/:id', to: 'order_menu_items#destroy'

  get 'payments/success', to: 'payments#success'
  post 'payments/webhook', to: 'payments#webhook'

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/order_menu_item.rb
class OrderMenuItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item

  def total_price
    return menu_item.price * quantity
  end
end

app/controllers/order_menu_items_controller.rb
class OrderMenuItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order
  before_action :set_order_item, only: [:update, :destroy]
  before_action :set_order_items, only: [:index, :destroy_all_items]

  def index
    # Adding Stripe Checkout session only for customers with items added in the order
    if user_signed_in? && current_user.has_role?(:customer) && !@order_items.empty?
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          name: 'VegMe Order',
          description: "Meal from #{@order.menu_items.first.user.full_name}",
          images: ['https://res.cloudinary.com/limagisele/image/upload/v1652509895/VegMe_ljjeph.png'],
          amount: (@order.order_total_price * 100).to_i,
          currency: 'aud',
          quantity: 1
        }],
        payment_intent_data: {
          metadata: {
            order_id: @order.id,
            user_id: current_user.id
          }
        },
        success_url: "#{root_url}payments/success?orderId=#{@order.id}",
        cancel_url: "#{root_url}order_menu_items"
      )
      @session_id = session.id
    end
  end

  def create
    @order_item = @order.order_menu_items.create!(order_item_params)
    redirect_to order_menu_items_path
  end

  def update
    @order_item.update!(order_item_params)
    redirect_to order_menu_items_path
  end

  def destroy
    @order_item.destroy
    redirect_to order_menu_items_path
  end

  def destroy_all_items
    @order_items.destroy_all
    redirect_to order_menu_items_path
  end

  private

  # Setting a session-based order for the current user when accessing the 'View Order' page
  def set_order
    @order = Order.find(session[:order_id])
  rescue ActiveRecord::RecordNotFound
    @order = Order.create(user_id: current_user.id)
    session[:order_id] = @order.id
  end

  def set_order_items
    # Creating a variable with all order_menu_items included in the current order
    # Querying only the required attributes for view and actions
    @order_items = @order.order_menu_items.select(:id, :menu_item_id, :quantity)
  end

  def set_order_item
    # Creating a variable with a specific order_menu_item from the current order
    # Querying only the required attributes for view and actions
    @order_item = @order.order_menu_items.select(:id, :order_id, :menu_item_id, :quantity).find(params[:id])
  end

  # Strong params for creating/updating an instance of OrderMenuItem
  def order_item_params
    return params.require(:order_menu_item).permit(:order_id, :menu_item_id, :quantity)
  end

end

app/helpers/order_menu_items_helper.rb
module OrderMenuItemsHelper
end

app/views/order_menu_items/index.html.erb
<h1>Order</h1>

<% if @order_items.empty? %>
  <p>You don't have items in your order yet!</p>
<% else %>
	<div class="table-responsive">
		<table class="table table-borderless">
			<thead>
				<tr>
					<th scope="col">Item</th>
					<th scope="col">Price</th>
					<th scope="col">Quantity</th>
					<th scope="col">Subtotal</th>
				</tr>
			</thead>
			<tbody>
				<% @order_items.each do |item| %>
					<tr>
						<td class="text-nowrap"><%= item.menu_item.name %></td>
						<td>$<%= item.menu_item.price %></td>
						<td>
							<%= form_with(model: item, url: "/order_menu_items/#{item.id}") do |f| %>
								<%= f.hidden_field :menu_item_id, value: item.menu_item.id %>
								<%= f.number_field :quantity, value: item.quantity, in: 1..20 %>
								<%= button_to("", order_menu_items_path(item.id), class: 'btn btn-outline-primary btn-sm bi bi-pencil') %>
							<% end %>
						</td>
						<td>$<%= item.total_price %></td>
						<td>
							<%= form_with(model: item, url: "/order_menu_items/#{item.id}") do |f| %>
								<%= button_to('', order_menu_items_path(item.id), class: 'btn btn-outline-danger btn-sm bi bi-trash', method: :delete) %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<hr>

	<h6>Total Order: $<%= @order.order_total_price %></h6>

	<div class='btn-toolbar'>
		<button data-stripe="payment" class="btn btn-success btn-sm me-3 my-3">Complete Order <%= number_to_currency(@order.order_total_price) %></button>
		<%= button_to('Delete Order', destroy_all_items_path, class: 'btn btn-danger btn-sm my-3', method: :delete) %>
	</div>

	<%= link_to 'Back to Menu', menu_path(@order_items[0].menu_item.user_id) %>
	
	<script src="https://js.stripe.com/v3/"></script>
	<script>
		document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
			const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
			stripe.redirectToCheckout({
					sessionId: "<%= @session_id %>"
			});
		});
	</script>
<% end %>